import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

/// Localized string dictionaries for all 4 supported languages.
class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    // ==========================================
    // 1. ENGLISH (Default)
    // ==========================================
    'en': {
      // General
      'app_name': 'AgriMed Link',
      'language': 'Language',
      'select_language': 'Select Language',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'search': 'Search',
      'all': 'All',
      'filter': 'Filter',
      'status': 'Status',
      'loading': 'Loading...',
      'success': 'Success',
      'error': 'Error',
      'close': 'Close',
      'confirm': 'Confirm',
      'no_data': 'No items found',

      // Auth
      'welcome_back': 'Welcome Back',
      'sign_in_subtitle': 'Sign in to access your agricultural network',
      'email_address': 'Email Address',
      'enter_email': 'Enter your email',
      'password': 'Password',
      'enter_password': 'Enter your password',
      'confirm_password': 'Confirm Password',
      'forgot_password': 'Forgot Password?',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'dont_have_account': "Don't have an account?",
      'already_have_account': 'Already have an account?',
      'join_agrimed': 'Join AgriMed Link',
      'join_subtitle': 'Connect directly with verified farmers, buyers, and suppliers',
      'full_name': 'Full Name',
      'enter_full_name': 'Enter your full name',
      'select_role': 'Select Your Role',
      'role_buyer': 'Buyer',
      'role_farmer': 'Farmer',
      'role_supplier': 'Supplier',
      'role_admin': 'Admin',
      'role_advisor': 'Advisor',
      'role_investor': 'Investor',
      'role_buyer_desc': 'Source fresh produce and medicinal crops',
      'role_farmer_desc': 'Sell your harvest directly to market',
      'role_supplier_desc': 'Provide farming tools, seeds, and fertilizer',
      'role_admin_desc': 'System oversight, verification & user management',
      'role_advisor_desc': 'Offer professional consultations & agronomy tips',
      'role_investor_desc': 'Fund farming activities & collect returns',
      'register_as': 'Register as {role}',
      'register_as_admin': 'Register as Admin',
      'agree_terms': 'By continuing, you agree to our Terms of Service & Privacy Policy',
      'signing_in': 'Signing in...',
      'creating_account': 'Creating account...',

      // Navigation & Roles
      'nav_products': 'Products',
      'nav_crops': 'Crops',
      'nav_scan': 'Scan',
      'nav_maps': 'Farm & Delivery Map',
      'nav_orders': 'Orders',
      'nav_profile': 'Profile',
      'nav_settings': 'Settings',
      'nav_logout': 'Logout',
      'nav_language': 'Language',
      'role_badge_farmer': 'FARMER',
      'role_badge_buyer': 'BUYER',
      'role_badge_supplier': 'SUPPLIER',
      'role_badge_admin': 'ADMIN',
      'role_badge_advisor': 'ADVISOR',
      'role_badge_investor': 'INVESTOR',

      // Products Tab
      'marketplace_products': 'Marketplace Products',
      'featured_supplies': 'Featured Supplies',
      'search_products': 'Search products, equipment, seeds...',
      'cat_all': 'All',
      'cat_herbs': 'Herbs',
      'cat_seeds': 'Seeds',
      'cat_equipment': 'Equipment',
      'add_to_cart': 'Add to Cart',
      'in_stock': 'In Stock',
      'out_of_stock': 'Out of Stock',

      // Crops Tab & Management
      'medicinal_crops': 'Medicinal Crops',
      'medicinal_crops_subtitle': 'Verified farm-direct medicinal & organic harvest listings',
      'search_crops': 'Search crops, botanicals, farmers...',
      'tab_marketplace': 'Marketplace',
      'tab_my_farm': 'My Farm',
      'add_crop': 'Add Crop',
      'bulk_upload': 'Bulk Upload',
      'add_or_upload': 'Add / Upload',
      'add_new_crop': 'Add New Crop',
      'edit_crop': 'Edit Crop',
      'delete_crop': 'Delete Crop',
      'crop_name': 'Crop Name',
      'category': 'Category',
      'price_dollar': 'Price (\$) *',
      'quantity_in_stock': 'Quantity in Stock',
      'unit': 'Unit',
      'description': 'Description',
      'image_url': 'Image URL (Optional)',
      'or_choose_preset': 'Or Choose Preset Icon',
      'save_crop': 'Save Crop',
      'update_crop': 'Update Crop',
      'delete_crop_confirm': 'Are you sure you want to delete this crop?',
      'delete_crop_warning': 'This action cannot be undone and will remove the crop from the active marketplace.',
      'bulk_import_crops': 'Bulk Import Crops',
      'import_crops_btn': 'Import Crops',
      'crop_added_success': 'Crop added successfully!',
      'crop_updated_success': 'Crop updated successfully!',
      'crop_deleted_success': 'Crop deleted successfully!',
      'batch_imported_success': 'batch crops imported successfully!',

      // Currency & Multi-Exchange
      'currency': 'Currency',
      'currency_converter': 'Currency Converter',
      'currency_fcfa': 'Franc CFA (FCFA)',
      'currency_eur': 'Euro (€)',
      'currency_usd': 'US Dollar (\$)',
      'active_currency': 'Active Currency',
      'nav_currency': 'Currency',

      // Scan Tab
      'scan_title': 'Scan Crop/Product',
      'scan_heading': 'Smart Crop & Health Scanner',
      'scan_subtitle': 'Scan live crops or upload images for botanical ID, disease diagnosis & valuation',
      'scan_mode_camera': 'Camera Viewfinder',
      'scan_mode_upload': 'Upload Image',
      'scan_capture_btn': 'Capture & Analyze',
      'scan_upload_btn': 'Select Image to Scan',
      'scan_choose_specimen': 'Pick Specimen',
      'scan_diagnosis_complete': 'Diagnostic Scan Complete',
      'scan_health_status': 'Health Status',
      'scan_active_compounds': 'Active Phytochemicals',
      'scan_market_value': 'Estimated Market Valuation',

      // Admin Portal & Operations
      'nav_admin_portal': 'Admin Portal',
      'admin_portal_title': 'Admin Management Console',
      'admin_portal_subtitle': 'System statistics, user governance, and professional approvals',
      'admin_tab_stats': 'Statistics',
      'admin_tab_users': 'Users',
      'admin_tab_requests': 'Approvals',
      'admin_tab_settings': 'App Settings',
      'stat_total_users': 'Total Users',
      'stat_active_crops': 'Active Crops',
      'stat_pending_approvals': 'Pending Approvals',
      'stat_server_uptime': 'Server Uptime',
      'stat_db_status': 'Database Status',
      'stat_memory': 'Memory Used',
      'stat_suspended_users': 'Suspended Users',
      'user_search_placeholder': 'Search users by name, email, phone...',
      'create_user_btn': 'Create User',
      'suspend_btn': 'Suspend',
      'unsuspend_btn': 'Un-suspend',
      'accept_btn': 'Accept Request',
      'reject_btn': 'Reject Request',
      'status_active': 'ACTIVE',
      'status_suspended': 'SUSPENDED',
      'status_pending': 'PENDING',
      'status_rejected': 'REJECTED',
      'maintenance_mode': 'Maintenance Mode',
      'announcement_banner': 'Platform Announcement',
      'commission_rate': 'Commission Rate (%)',
      'save_settings_btn': 'Save Application Settings',
      'settings_saved_success': 'Application settings updated successfully!',
      'user_created_success': 'User created successfully!',
      'user_suspended_success': 'User has been suspended',
      'user_unsuspended_success': 'User has been un-suspended',
      'request_accepted_success': 'Professional account approved & activated!',
      'request_rejected_success': 'Registration request rejected',
      'no_pending_requests': 'No pending account requests at this time',
      'role_distribution': 'Role Distribution',
      'system_health_overview': 'System Health & Metrics',
    },

    // ==========================================
    // 2. FRENCH (Français)
    // ==========================================
    'fr': {
      // General
      'app_name': 'AgriMed Link',
      'language': 'Langue',
      'select_language': 'Choisir la langue',
      'cancel': 'Annuler',
      'save': 'Enregistrer',
      'delete': 'Supprimer',
      'edit': 'Modifier',
      'search': 'Rechercher',
      'all': 'Tous',
      'filter': 'Filtrer',
      'status': 'Statut',
      'loading': 'Chargement...',
      'success': 'Succès',
      'error': 'Erreur',
      'close': 'Fermer',
      'confirm': 'Confirmer',
      'no_data': 'Aucun élément trouvé',

      // Auth
      'welcome_back': 'Bon retour',
      'sign_in_subtitle': 'Connectez-vous pour accéder à votre réseau agricole',
      'email_address': 'Adresse e-mail',
      'enter_email': 'Entrez votre e-mail',
      'password': 'Mot de passe',
      'enter_password': 'Entrez votre mot de passe',
      'confirm_password': 'Confirmer le mot de passe',
      'forgot_password': 'Mot de passe oublié ?',
      'sign_in': 'Se connecter',
      'sign_up': "S'inscrire",
      'dont_have_account': "Vous n'avez pas de compte ?",
      'already_have_account': 'Vous avez déjà un compte ?',
      'join_agrimed': 'Rejoignez AgriMed Link',
      'join_subtitle': 'Connectez-vous directement avec des agriculteurs et acheteurs certifiés',
      'full_name': 'Nom complet',
      'enter_full_name': 'Entrez votre nom complet',
      'select_role': 'Choisissez votre rôle',
      'role_buyer': 'Acheteur',
      'role_farmer': 'Agriculteur',
      'role_supplier': 'Fournisseur',
      'role_admin': 'Administrateur',
      'role_advisor': 'Conseiller',
      'role_investor': 'Investisseur',
      'role_buyer_desc': 'Achetez des produits frais et cultures médicinales',
      'role_farmer_desc': 'Vendez vos récoltes directement sur le marché',
      'role_supplier_desc': 'Fournissez outils, semences et engrais',
      'role_admin_desc': 'Supervision du système, vérification et gestion',
      'role_advisor_desc': 'Offrez des conseils agricoles professionnels et astuces',
      'role_investor_desc': 'Financez les activités agricoles et récoltes',
      'register_as': "S'inscrire en tant que {role}",
      'register_as_admin': "S'inscrire en tant qu'administrateur",
      'agree_terms': "En continuant, vous acceptez nos conditions d'utilisation",
      'signing_in': 'Connexion en cours...',
      'creating_account': 'Création du compte...',

      // Navigation & Roles
      'nav_products': 'Produits',
      'nav_crops': 'Cultures',
      'nav_scan': 'Scanner',
      'nav_maps': 'Carte des Fermes & Livraison',
      'nav_orders': 'Commandes',
      'nav_profile': 'Profil',
      'nav_settings': 'Paramètres',
      'nav_logout': 'Déconnexion',
      'nav_language': 'Langue',
      'role_badge_farmer': 'AGRICULTEUR',
      'role_badge_buyer': 'ACHETEUR',
      'role_badge_supplier': 'FOURNISSEUR',
      'role_badge_admin': 'ADMINISTRATEUR',
      'role_badge_advisor': 'CONSEILLER',
      'role_badge_investor': 'INVESTISSEUR',

      // Products Tab
      'marketplace_products': 'Produits du marché',
      'featured_supplies': 'Fournitures en vedette',
      'search_products': 'Rechercher produits, matériel, semences...',
      'cat_all': 'Tous',
      'cat_herbs': 'Plantes',
      'cat_seeds': 'Semences',
      'cat_equipment': 'Équipement',
      'add_to_cart': 'Ajouter au panier',
      'in_stock': 'En stock',
      'out_of_stock': 'En rupture',

      // Crops Tab & Management
      'medicinal_crops': 'Cultures médicinales',
      'medicinal_crops_subtitle': 'Annonces directes des exploitations agricoles vérifiées',
      'search_crops': 'Rechercher cultures, plantes, agriculteurs...',
      'tab_marketplace': 'Marché',
      'tab_my_farm': 'Ma ferme',
      'add_crop': 'Ajouter culture',
      'bulk_upload': 'Import groupé',
      'add_or_upload': 'Ajouter / Téléverser',
      'add_new_crop': 'Ajouter une nouvelle culture',
      'edit_crop': 'Modifier la culture',
      'delete_crop': 'Supprimer la culture',
      'crop_name': 'Nom de la culture',
      'category': 'Catégorie',
      'price_dollar': 'Prix (\$) *',
      'quantity_in_stock': 'Quantité en stock',
      'unit': 'Unité',
      'description': 'Description',
      'image_url': "URL de l'image (Optionnel)",
      'or_choose_preset': 'Ou choisir une icône prédéfinie',
      'save_crop': 'Enregistrer la culture',
      'update_crop': 'Mettre à jour la culture',
      'delete_crop_confirm': 'Êtes-vous sûr de vouloir supprimer cette culture ?',
      'delete_crop_warning': 'Cette action est irréversible et retirera le produit du marché actif.',
      'bulk_import_crops': 'Importer des cultures en bloc',
      'import_crops_btn': 'Importer les cultures',
      'crop_added_success': 'Culture ajoutée avec succès !',
      'crop_updated_success': 'Culture mise à jour avec succès !',
      'crop_deleted_success': 'Culture supprimée avec succès !',
      'batch_imported_success': 'cultures groupées importées avec succès !',

      // Devise & Multi-Change
      'currency': 'Devise',
      'currency_converter': 'Convertisseur de Devises',
      'currency_fcfa': 'Franc CFA (FCFA)',
      'currency_eur': 'Euro (€)',
      'currency_usd': 'Dollar US (\$)',
      'active_currency': 'Devise Active',
      'nav_currency': 'Devise',

      // Scan Tab
      'scan_title': 'Scanner Intelligent de Plantes',
      'scan_subtitle': 'Scannez en direct ou téléversez des images pour analyse botanique, diagnostic et estimation',
      'scan_mode_camera': 'Viseur Caméra',
      'scan_mode_upload': 'Téléverser Image',
      'scan_capture_btn': 'Capturer et Analyser',
      'scan_upload_btn': 'Sélectionner une Image à Scanner',
      'scan_choose_specimen': 'Choisir Spécimen',
      'scan_diagnosis_complete': 'Diagnostic Complet',
      'scan_health_status': 'État Sanitaire',
      'scan_active_compounds': 'Phytochimiques Actifs',
      'scan_market_value': 'Valeur Estimée sur le Marché',

      // Admin Portal & Operations
      'nav_admin_portal': 'Portail Admin',
      'admin_portal_title': "Console d'administration",
      'admin_portal_subtitle': 'Statistiques système, gouvernance des utilisateurs et approbations',
      'admin_tab_stats': 'Statistiques',
      'admin_tab_users': 'Utilisateurs',
      'admin_tab_requests': 'Approbations',
      'admin_tab_settings': 'Paramètres App',
      'stat_total_users': 'Total Utilisateurs',
      'stat_active_crops': 'Cultures Actives',
      'stat_pending_approvals': 'En Attente',
      'stat_server_uptime': 'Temps de fonctionnement',
      'stat_db_status': 'État Base de données',
      'stat_memory': 'Mémoire utilisée',
      'stat_suspended_users': 'Comptes suspendus',
      'user_search_placeholder': 'Rechercher par nom, email, téléphone...',
      'create_user_btn': 'Créer utilisateur',
      'suspend_btn': 'Suspendre',
      'unsuspend_btn': 'Réactiver',
      'accept_btn': 'Accepter la demande',
      'reject_btn': 'Rejeter la demande',
      'status_active': 'ACTIF',
      'status_suspended': 'SUSPENDU',
      'status_pending': 'EN ATTENTE',
      'status_rejected': 'REJETÉ',
      'maintenance_mode': 'Mode Maintenance',
      'announcement_banner': 'Annonce de la plateforme',
      'commission_rate': 'Taux de commission (%)',
      'save_settings_btn': "Enregistrer les paramètres",
      'settings_saved_success': 'Paramètres de la plateforme mis à jour avec succès !',
      'user_created_success': 'Utilisateur créé avec succès !',
      'user_suspended_success': "L'utilisateur a été suspendu",
      'user_unsuspended_success': "L'utilisateur a été réactivé",
      'request_accepted_success': 'Compte professionnel approuvé et activé !',
      'request_rejected_success': "Demande d'inscription rejetée",
      'no_pending_requests': 'Aucune demande en attente actuellement',
      'role_distribution': 'Répartition par rôle',
      'system_health_overview': 'État et métriques du système',
    },

    // ==========================================
    // 3. SPANISH (Español)
    // ==========================================
    'es': {
      // General
      'app_name': 'AgriMed Link',
      'language': 'Idioma',
      'select_language': 'Seleccionar idioma',
      'cancel': 'Cancelar',
      'save': 'Guardar',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'search': 'Buscar',
      'all': 'Todos',
      'filter': 'Filtrar',
      'status': 'Estado',
      'loading': 'Cargando...',
      'success': 'Éxito',
      'error': 'Error',
      'close': 'Cerrar',
      'confirm': 'Confirmar',
      'no_data': 'No se encontraron elementos',

      // Auth
      'welcome_back': 'Bienvenido de nuevo',
      'sign_in_subtitle': 'Inicie sesión para acceder a su red agrícola',
      'email_address': 'Correo electrónico',
      'enter_email': 'Ingrese su correo electrónico',
      'password': 'Contraseña',
      'enter_password': 'Ingrese su contraseña',
      'confirm_password': 'Confirmar contraseña',
      'forgot_password': '¿Olvidó su contraseña?',
      'sign_in': 'Iniciar sesión',
      'sign_up': 'Registrarse',
      'dont_have_account': '¿No tiene una cuenta?',
      'already_have_account': '¿Ya tiene una cuenta?',
      'join_agrimed': 'Únase a AgriMed Link',
      'join_subtitle': 'Conéctese directamente con agricultores y compradores certificados',
      'full_name': 'Nombre completo',
      'enter_full_name': 'Ingrese su nombre completo',
      'select_role': 'Seleccione su rol',
      'role_buyer': 'Comprador',
      'role_farmer': 'Agricultor',
      'role_supplier': 'Proveedor',
      'role_admin': 'Administrador',
      'role_advisor': 'Asesor',
      'role_investor': 'Inversionista',
      'role_buyer_desc': 'Obtenga productos frescos y cultivos medicinales',
      'role_farmer_desc': 'Venda su cosecha directamente en el mercado',
      'role_supplier_desc': 'Provea herramientas, semillas y fertilizantes',
      'role_admin_desc': 'Supervisión del sistema, verificación y gestión',
      'role_advisor_desc': 'Ofrezca consultas agrícolas profesionales y consejos',
      'role_investor_desc': 'Financie actividades agrícolas y ciclos de cosecha',
      'register_as': 'Registrarse como {role}',
      'register_as_admin': 'Registrarse como Administrador',
      'agree_terms': 'Al continuar, acepta nuestros Términos de servicio y Privacidad',
      'signing_in': 'Iniciando sesión...',
      'creating_account': 'Creando cuenta...',

      // Navigation & Roles
      'nav_products': 'Productos',
      'nav_crops': 'Cultivos',
      'nav_scan': 'Escanear',
      'nav_maps': 'Mapa de Granjas y Entrega',
      'nav_orders': 'Pedidos',
      'nav_profile': 'Perfil',
      'nav_settings': 'Configuración',
      'nav_logout': 'Cerrar sesión',
      'nav_language': 'Idioma',
      'role_badge_farmer': 'AGRICULTOR',
      'role_badge_buyer': 'COMPRADOR',
      'role_badge_supplier': 'PROVEEDOR',
      'role_badge_admin': 'ADMINISTRADOR',
      'role_badge_advisor': 'ASESOR',
      'role_badge_investor': 'INVERSIONISTA',

      // Products Tab
      'marketplace_products': 'Productos del mercado',
      'featured_supplies': 'Suministros destacados',
      'search_products': 'Buscar productos, equipos, semillas...',
      'cat_all': 'Todos',
      'cat_herbs': 'Hierbas',
      'cat_seeds': 'Semillas',
      'cat_equipment': 'Equipos',
      'add_to_cart': 'Añadir al carrito',
      'in_stock': 'En existencias',
      'out_of_stock': 'Agotado',

      // Crops Tab & Management
      'medicinal_crops': 'Cultivos medicinales',
      'medicinal_crops_subtitle': 'Listados directos de granjas certificadas y cosechas orgánicas',
      'search_crops': 'Buscar cultivos, botánicos, agricultores...',
      'tab_marketplace': 'Mercado',
      'tab_my_farm': 'Mi granja',
      'add_crop': 'Añadir cultivo',
      'bulk_upload': 'Carga masiva',
      'add_or_upload': 'Añadir / Subir',
      'add_new_crop': 'Añadir nuevo cultivo',
      'edit_crop': 'Editar cultivo',
      'delete_crop': 'Eliminar cultivo',
      'crop_name': 'Nombre del cultivo',
      'category': 'Categoría',
      'price_dollar': 'Precio (\$) *',
      'quantity_in_stock': 'Cantidad en existencia',
      'unit': 'Unidad',
      'description': 'Descripción',
      'image_url': 'URL de imagen (Opcional)',
      'or_choose_preset': 'O elija un icono predefinido',
      'save_crop': 'Guardar cultivo',
      'update_crop': 'Actualizar cultivo',
      'delete_crop_confirm': '¿Está seguro de que desea eliminar este cultivo?',
      'delete_crop_warning': 'Esta acción no se puede deshacer y retirará el cultivo del mercado activo.',
      'bulk_import_crops': 'Importación masiva de cultivos',
      'import_crops_btn': 'Importar cultivos',
      'crop_added_success': '¡Cultivo añadido con éxito!',
      'crop_updated_success': '¡Cultivo actualizado con éxito!',
      'crop_deleted_success': '¡Cultivo eliminado con éxito!',
      'batch_imported_success': 'cultivos por lote importados con éxito!',

      // Moneda & Multi-Cambio
      'currency': 'Moneda',
      'currency_converter': 'Convertidor de Monedas',
      'currency_fcfa': 'Franco CFA (FCFA)',
      'currency_eur': 'Euro (€)',
      'currency_usd': 'Dólar Estadounidense (\$)',
      'active_currency': 'Moneda Activa',
      'nav_currency': 'Moneda',

      // Scan Tab
      'scan_title': 'Escáner Inteligente de Cultivos',
      'scan_subtitle': 'Escanee cultivos en vivo o suba imágenes para identificación botánica, diagnóstico y valoración',
      'scan_mode_camera': 'Visor de Cámara',
      'scan_mode_upload': 'Subir Imagen',
      'scan_capture_btn': 'Capturar y Analizar',
      'scan_upload_btn': 'Seleccionar Imagen para Escanear',
      'scan_choose_specimen': 'Elegir Espécimen',
      'scan_diagnosis_complete': 'Diagnóstico Completado',
      'scan_health_status': 'Estado de Salud',
      'scan_active_compounds': 'Fitoquímicos Activos',
      'scan_market_value': 'Valoración Estimada de Mercado',

      // Admin Portal & Operations
      'nav_admin_portal': 'Portal Admin',
      'admin_portal_title': 'Consola de Administración',
      'admin_portal_subtitle': 'Estadísticas del sistema, gestión de usuarios y aprobaciones',
      'admin_tab_stats': 'Estadísticas',
      'admin_tab_users': 'Usuarios',
      'admin_tab_requests': 'Aprobaciones',
      'admin_tab_settings': 'Ajustes App',
      'stat_total_users': 'Total Usuarios',
      'stat_active_crops': 'Cultivos Activos',
      'stat_pending_approvals': 'Pendientes',
      'stat_server_uptime': 'Tiempo de actividad',
      'stat_db_status': 'Estado BD',
      'stat_memory': 'Memoria en uso',
      'stat_suspended_users': 'Suspendidos',
      'user_search_placeholder': 'Buscar por nombre, email, teléfono...',
      'create_user_btn': 'Crear usuario',
      'suspend_btn': 'Suspender',
      'unsuspend_btn': 'Reactivar',
      'accept_btn': 'Aceptar solicitud',
      'reject_btn': 'Rechazar solicitud',
      'status_active': 'ACTIVO',
      'status_suspended': 'SUSPENDIDO',
      'status_pending': 'PENDIENTE',
      'status_rejected': 'RECHAZADO',
      'maintenance_mode': 'Modo de mantenimiento',
      'announcement_banner': 'Anuncio de la plataforma',
      'commission_rate': 'Tasa de comisión (%)',
      'save_settings_btn': 'Guardar configuración',
      'settings_saved_success': '¡Configuración de la plataforma actualizada!',
      'user_created_success': '¡Usuario creado exitosamente!',
      'user_suspended_success': 'El usuario ha sido suspendido',
      'user_unsuspended_success': 'El usuario ha sido reactivado',
      'request_accepted_success': '¡Cuenta profesional aprobada y activada!',
      'request_rejected_success': 'Solicitud de registro rechazada',
      'no_pending_requests': 'No hay solicitudes pendientes en este momento',
      'role_distribution': 'Distribución por rol',
      'system_health_overview': 'Salud y métricas del sistema',
    },

    // ==========================================
    // 4. ARABIC (العربية)
    // ==========================================
    'ar': {
      // General
      'app_name': 'AgriMed Link',
      'language': 'اللغة',
      'select_language': 'اختر اللغة',
      'cancel': 'إلغاء',
      'save': 'حفظ',
      'delete': 'حذف',
      'edit': 'تعديل',
      'search': 'بحث',
      'all': 'الكل',
      'filter': 'تصفية',
      'status': 'الحالة',
      'loading': 'جاري التحميل...',
      'success': 'نجاح',
      'error': 'خطأ',
      'close': 'إغلاق',
      'confirm': 'تأكيد',
      'no_data': 'لم يتم العثور على عناصر',

      // Auth
      'welcome_back': 'أهلاً بك من جديد',
      'sign_in_subtitle': 'سجّل الدخول للوصول إلى شبكتك الزراعية',
      'email_address': 'البريد الإلكتروني',
      'enter_email': 'أدخل بريدك الإلكتروني',
      'password': 'كلمة المرور',
      'enter_password': 'أدخل كلمة المرور',
      'confirm_password': 'تأكيد كلمة المرور',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'sign_in': 'تسجيل الدخول',
      'sign_up': 'إنشاء حساب',
      'dont_have_account': 'ليس لديك حساب؟',
      'already_have_account': 'هل لديك حساب بالفعل؟',
      'join_agrimed': 'انضم إلى AgriMed Link',
      'join_subtitle': 'تواصل مباشرة مع المزارعين والمشترين والموردين المعتمدين',
      'full_name': 'الاسم الكامل',
      'enter_full_name': 'أدخل اسمك الكامل',
      'select_role': 'اختر دورك',
      'role_buyer': 'مشتري',
      'role_farmer': 'مزارع',
      'role_supplier': 'مورد',
      'role_admin': 'مدير',
      'role_advisor': 'مستشار',
      'role_investor': 'مستثمر',
      'role_buyer_desc': 'شراء المنتجات الطازجة والمحاصيل الطبية',
      'role_farmer_desc': 'بيع محاصيلك مباشرة في السوق',
      'role_supplier_desc': 'توفير الأدوات الزراعية والبذور والأسمدة',
      'role_admin_desc': 'الإشراف على النظام، التحقق من المحاصيل وإدارة المنصة',
      'role_advisor_desc': 'تقديم استشارات زراعية مهنية وإرشادات متخصصة',
      'role_investor_desc': 'تمويل الأنشطة الزراعية ومواسم الحصاد وتحصيل العوائد',
      'register_as': 'التسجيل كـ {role}',
      'register_as_admin': 'التسجيل كـ مدير',
      'agree_terms': 'بالمتابعة، فإنك توافق على شروط الخدمة وسياسة الخصوصية',
      'signing_in': 'جاري تسجيل الدخول...',
      'creating_account': 'جاري إنشاء الحساب...',

      // Navigation & Roles
      'nav_products': 'المنتجات',
      'nav_crops': 'المحاصيل',
      'nav_scan': 'مسح',
      'nav_maps': 'خريطة المزارع والتوصيل',
      'nav_orders': 'الطلبات',
      'nav_profile': 'الملف الشخصي',
      'nav_settings': 'الإعدادات',
      'nav_logout': 'تسجيل الخروج',
      'nav_language': 'اللغة',
      'role_badge_farmer': 'مزارع',
      'role_badge_buyer': 'مشتري',
      'role_badge_supplier': 'مورد',
      'role_badge_admin': 'مدير',
      'role_badge_advisor': 'مستشار',
      'role_badge_investor': 'مستثمر',

      // Products Tab
      'marketplace_products': 'منتجات السوق',
      'featured_supplies': 'الإمدادات المميزة',
      'search_products': 'ابحث عن المنتجات والمعدات والبذور...',
      'cat_all': 'الكل',
      'cat_herbs': 'أعشاب',
      'cat_seeds': 'بذور',
      'cat_equipment': 'معدات',
      'add_to_cart': 'أضف إلى السلة',
      'in_stock': 'متوفر',
      'out_of_stock': 'غير متوفر',

      // Crops Tab & Management
      'medicinal_crops': 'المحاصيل الطبية',
      'medicinal_crops_subtitle': 'محاصيل طبية وعضوية موثقة ومباشرة من المزارع',
      'search_crops': 'ابحث عن المحاصيل والنباتات والمزارعين...',
      'tab_marketplace': 'السوق',
      'tab_my_farm': 'مزرعتي',
      'add_crop': 'إضافة محصول',
      'bulk_upload': 'رفع دفعات',
      'add_or_upload': 'إضافة / رفع',
      'add_new_crop': 'إضافة محصول جديد',
      'edit_crop': 'تعديل المحصول',
      'delete_crop': 'حذف المحصول',
      'crop_name': 'اسم المحصول',
      'category': 'الفئة',
      'price_dollar': 'السعر (\$) *',
      'quantity_in_stock': 'الكمية المتوفرة',
      'unit': 'الوحدة',
      'description': 'الوصف',
      'image_url': 'رابط الصورة (اختياري)',
      'or_choose_preset': 'أو اختر أيقونة جاهزة',
      'save_crop': 'حفظ المحصول',
      'update_crop': 'تحديث المحصول',
      'delete_crop_confirm': 'هل أنت متأكد من رغبتك في حذف هذا المحصول؟',
      'delete_crop_warning': 'لا يمكن التراجع عن هذا الإجراء وسيتم إزالة المحصول من السوق.',
      'bulk_import_crops': 'استيراد المحاصيل دفعة واحدة',
      'import_crops_btn': 'استيراد المحاصيل',
      'crop_added_success': 'تم إضافة المحصول بنجاح!',
      'crop_updated_success': 'تم تحديث المحصول بنجاح!',
      'crop_deleted_success': 'تم حذف المحصول بنجاح!',
      'batch_imported_success': 'محاصيل مجمعة تم استيرادها بنجاح!',

      // العملة وتحويل العملات
      'currency': 'العملة',
      'currency_converter': 'محول العملات',
      'currency_fcfa': 'فرنك سيفا (FCFA)',
      'currency_eur': 'يورو (€)',
      'currency_usd': 'دولار أمريكي (\$)',
      'active_currency': 'العملة النشطة',
      'nav_currency': 'العملة',

      // Scan Tab
      'scan_title': 'الماسح الذكي للمحاصيل',
      'scan_subtitle': 'امسح المحاصيل الحية أو ارفع الصور للتعرف النباتي وتشخيص الأمراض وتقدير الأسعار',
      'scan_mode_camera': 'محدد الكاميرا',
      'scan_mode_upload': 'تحميل صورة',
      'scan_capture_btn': 'التقاط وتحليل',
      'scan_upload_btn': 'اختر صورة للمسح',
      'scan_choose_specimen': 'اختر عينة',
      'scan_diagnosis_complete': 'اكتمل الفحص والتشخيص',
      'scan_health_status': 'الحالة الصحية',
      'scan_active_compounds': 'المركبات الكيميائية النباتية',
      'scan_market_value': 'القيمة السوقية التقديرية',

      // Admin Portal & Operations
      'nav_admin_portal': 'بوابة المسؤول',
      'admin_portal_title': 'لوحة تحكم المسؤول',
      'admin_portal_subtitle': 'إحصائيات النظام، إدارة المستخدمين، والموافقات المهنية',
      'admin_tab_stats': 'الإحصائيات',
      'admin_tab_users': 'المستخدمين',
      'admin_tab_requests': 'الموافقات',
      'admin_tab_settings': 'إعدادات التطبيق',
      'stat_total_users': 'إجمالي المستخدمين',
      'stat_active_crops': 'المحاصيل النشطة',
      'stat_pending_approvals': 'طلبات معلقة',
      'stat_server_uptime': 'وقت تشغيل الخادم',
      'stat_db_status': 'حالة قاعدة البيانات',
      'stat_memory': 'الذاكرة المستخدمة',
      'stat_suspended_users': 'المعلقين',
      'user_search_placeholder': 'البحث بالاسم، البريد أو الهاتف...',
      'create_user_btn': 'إنشاء مستخدم',
      'suspend_btn': 'تعليق',
      'unsuspend_btn': 'إلغاء التعليق',
      'accept_btn': 'قبول الطلب',
      'reject_btn': 'رفض الطلب',
      'status_active': 'نشط',
      'status_suspended': 'معلق',
      'status_pending': 'قيد المراجعة',
      'status_rejected': 'مرفوض',
      'maintenance_mode': 'وضع الصيانة',
      'announcement_banner': 'إعلان المنصة',
      'commission_rate': 'نسبة العمولة (%)',
      'save_settings_btn': 'حفظ إعدادات التطبيق',
      'settings_saved_success': 'تم حفظ إعدادات التطبيق بنجاح!',
      'user_created_success': 'تم إنشاء المستخدم بنجاح!',
      'user_suspended_success': 'تم تعليق حساب المستخدم',
      'user_unsuspended_success': 'تم إلغاء تعليق المستخدم وتفعيله',
      'request_accepted_success': 'تم قبول الحساب المهني وتفعيله بنجاح!',
      'request_rejected_success': 'تم رفض طلب التسجيل',
      'no_pending_requests': 'لا توجد طلبات معلقة حالياً',
      'role_distribution': 'توزيع الأدوار',
      'system_health_overview': 'حالة النظام والمقاييس',
    },
  };

  /// Translates a key for the current locale with optional parameter replacements.
  String translate(String key, [Map<String, String>? params]) {
    final langCode = locale.languageCode;
    String? translation = _localizedValues[langCode]?[key];

    // Fall back to English if key is missing in selected language
    translation ??= _localizedValues['en']?[key] ?? key;

    if (params != null) {
      params.forEach((paramKey, paramValue) {
        translation = translation!.replaceAll('{$paramKey}', paramValue);
      });
    }

    return translation!;
  }

  /// Safe static fallback when BuildContext has no active AppLocalizations.
  static String fallback(String key, [Map<String, String>? params]) {
    String translation = _localizedValues['en']?[key] ?? key;
    if (params != null) {
      params.forEach((paramKey, paramValue) {
        translation = translation.replaceAll('{$paramKey}', paramValue);
      });
    }
    return translation;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'fr', 'es', 'ar'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) {
    return SynchronousFuture<AppLocalizations>(AppLocalizations(locale));
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

/// Helper extension on [BuildContext] for ergonomic localization calls.
extension LocalizedContext on BuildContext {
  String tr(String key, [Map<String, String>? params]) {
    return AppLocalizations.of(this)?.translate(key, params) ??
        AppLocalizations.fallback(key, params);
  }
}
